name: enlatadora_web
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mqtt_client: ^10.11.11
  record: ^7.1.1
  flutter_dotenv: ^6.0.1
  google_fonts: ^8.2.1
  flutter_riverpod: ^3.3.1
  provider: ^6.1.5+1
  json_annotation: ^4.12.0
  http: ^1.6.0
  http_parser: ^4.1.2
  pcmtowave: ^0.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  json_serializable: ^6.9.0


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true
  assets:
    - .env

